### ISSUE TITLE
[Feat] 모든 화면 Coordinator 연결

### ISSUE THREAD

**Issue by Hansangjin98** [boostcampwm-2024/iOS05-Heim#107]
## 어떤 작업을 진행하나요? 🤔
- 모든 화면들의 Coordinator를 연결해 화면 전환을 구현합니다.

## 작업 상세 내용 📝
- 모든 Coordinator들 연결

**Comment by ParkSeongGeun** [comment]
PR Approve 이후 close 합니다.
- https://github.com/boostcampwm-2024/iOS05-Heim/pull/107
