### ISSUE TITLE
[Bug] Custom Font가 적용이 안 되는 문제

### ISSUE THREAD

**Issue by clxxrlove** [boostcampwm-2024/iOS05-Heim#13]
## 어떤 작업을 진행하나요? 🤔
- Custom Font이 적용이 안 되는 버그 수정

## 작업 상세 내용 📝
- info.plist 관련 이슈로 확인되어 수정 예정

**Comment by ParkSeongGeun** [comment]
Info.plist에 추가한 글꼴을 적어줘야 해당 문제 해결하는 거 같더라고요!
저도 찾아봤었어요 :)
-> [출처](https://cherry-bambi.tistory.com/2)
