### ISSUE TITLE
[Feat] DataStorage구현 

### ISSUE THREAD

**Issue by futuremirae** [boostcampwm-2024/iOS05-Heim#38]
## 어떤 작업을 진행하나요? 🤔
- 데이터 스토리지를 설계하고 구현합니다. 

## 작업 상세 내용 📝
-  데이터 스토리지 구현

## 예상 소요 시간 (Optional)
- 4h+

**Comment by ParkSeongGeun** [comment]
PR Approve 이후 close 합니다.
- https://github.com/boostcampwm-2024/iOS05-Heim/pull/46
